# Debug Configuration
MQTT_DEBUG = "NO"
TELEGRAM_DEBUG = "NO"

# MQTT Configuration
MQTT_BROKER = "192.168.89.100"
MQTT_PORT = 1883
MQTT_TOPICS = ["OpenwebRX/CLIENT", "OpenwebRX/RX"]
MQTT_USER = "openwebrx"
MQTT_PASSWORD = "XXXXXX"

# Telegram Configuration
TELEGRAM_TOKEN = "XXXXXXXX:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
CHAT_ID = "XXXXXXXX"
